import Footer from "./Footer";
import Header from "./Header";
import "./globals.css";

export const metadata = {
  title: "Real Human",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="bg-gray-100">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
