import Footer from "./Footer";
import Header from "./Header";
import "./globals.css";

export const metadata = {
  title: "Real Human",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <div className="bg-gray-100">
        <Header />

        <div>{children}</div>
        <Footer />
      </div>
    </html>
  );
}
